name: master

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  master:
    strategy:
      matrix:
        include:
          # linux
          - os: ubuntu-latest
            python: '3.10'
            toxenv: py
          - os: ubuntu-latest
            python: '3.11'
            toxenv: py
          # windows
          - os: windows-latest
            python: "3.10"
            toxenv: py
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python }}
    - run: python -m pip install --upgrade setuptools pip tox virtualenv
    - run: tox -e ${{ matrix.toxenv }}
